[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["wenet"]

[project]
name = "wenet"
version = "0.1.0"
license = { text = "CC BY" }